XML-Datei an Schema anpassen um Warnung zu beheben
[Fri Sep 27 22:53:08 CEST 2013][INFO][de.willuhn.jameica.hbci.passports.pintan.server.PassportHandleImpl.close] pin/tan passport closed
[Fri Sep 27 22:53:09 CEST 2013][INFO][de.willuhn.jameica.messaging.LogMessageConsumer.handleMessage] Sicherheits-Medium erfolgreich getestet.
[Fri Sep 27 22:53:09 CEST 2013][INFO][de.willuhn.jameica.hbci.gui.action.PassportTest$2.run] log target removed
Warning: validation was turned on but an org.xml.sax.ErrorHandler was not
set, which is probably not what is desired.  Parser will use a default
ErrorHandler to print the first 10 errors.  Please call
the 'setErrorHandler' method to fix this.
Error: URI=null Line=1320: Attribut "type" mit Wert "num" muss einen Wert aus der Liste "AN Bin Code Ctr Cur DTAUS Date Dig ID JN Num Time Wrt " haben.
Error: URI=null Line=1321: Attribut "type" mit Wert "num" muss einen Wert aus der Liste "AN Bin Code Ctr Cur DTAUS Date Dig ID JN Num Time Wrt " haben.
Error: URI=null Line=1322: Attribut "type" mit Wert "num" muss einen Wert aus der Liste "AN Bin Code Ctr Cur DTAUS Date Dig ID JN Num Time Wrt " haben.
Error: URI=null Line=1323: Attribut "type" mit Wert "num" muss einen Wert aus der Liste "AN Bin Code Ctr Cur DTAUS Date Dig ID JN Num Time Wrt " haben.
Error: URI=null Line=1327: Attribut "type" mit Wert "num" muss einen Wert aus der Liste "AN Bin Code Ctr Cur DTAUS Date Dig ID JN Num Time Wrt " haben.
Error: URI=null Line=1328: Attribut "type" mit Wert "num" muss einen Wert aus der Liste "AN Bin Code Ctr Cur DTAUS Date Dig ID JN Num Time Wrt " haben.
Error: URI=null Line=1329: Attribut "type" mit Wert "num" muss einen Wert aus der Liste "AN Bin Code Ctr Cur DTAUS Date Dig ID JN Num Time Wrt " haben.
Error: URI=null Line=1330: Attribut "type" mit Wert "num" muss einen Wert aus der Liste "AN Bin Code Ctr Cur DTAUS Date Dig ID JN Num Time Wrt " haben.
[Fri Sep 27 22:53:10 CEST 2013][INFO][de.willuhn.jameica.hbci.passports.pintan.server.PassportHandleImpl.getKonten] reading accounts from pin/tan passport